### ISSUE TITLE
USER STORY:View likes

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/logbook-p4#8]
As a **Site User / Admin** I can **view the number of likes on each post** so that I **can see which is the most popular or viral**.
### Accepatnce Criteria:

- Acceptance criteria 1:next to comments is the like button
- Acceptance criteria 2:the like button diplays the number of likes
- Accepatnce criteria 3:updates the number everytime its liked or clicked on it

### Tasks:

- [ ] adjust the design the screen size
- [ ] add a icon indicating the liked or disliked post
- [ ] test the response, the count of likes functions properly 
- [ ] test functionality

Iteration:#2
Points:#3
